# DHIS2 Configuration file (complete with default settings + Audit Vision additions)

# ----------------------------------------------------------------------
# Database connection
# ----------------------------------------------------------------------
connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql://dhis2-db/dhis
connection.username = dhis
connection.password = dhis

# Database schema behavior
connection.schema = update

# ----------------------------------------------------------------------
# Encryption
# ----------------------------------------------------------------------
encryption.password = xxxx

# ----------------------------------------------------------------------
# Audit configuration
# ----------------------------------------------------------------------
audit.metadata = CREATE;UPDATE;DELETE
audit.tracker = CREATE;UPDATE;DELETE
audit.aggregate = CREATE;UPDATE;DELETE

# Persistir audits na base de dados e em log
audit.database = on
audit.logger = on

# ----------------------------------------------------------------------
# App Hub
# ----------------------------------------------------------------------
#apphub.base.url = https://apps.dhis2.org
#apphub.api.url = https://apps.dhis2.org/api

# ----------------------------------------------------------------------
# Route API / Webhook integration
# ----------------------------------------------------------------------
route.remote_servers_allowed = http://api:8000

# ----------------------------------------------------------------------
# Event hooks
# ----------------------------------------------------------------------
event_hooks.enabled = on