# DHIS2 Configuration file (complete with default settings + Audit Vision additions)
connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql://dhis2-db/dhis
connection.username = dhis
connection.password = dhis
# Database schema behavior, can be validate, update, create, create-drop
connection.schema = update
encryption.password = xxxx
metadata.audit.persist = on
# URLs for specifying a custom app hub, these are the defaults
#apphub.base.url = https://apps.dhis2.org
#apphub.api.url = https://apps.dhis2.org/api

# Enable audit system for DHIS2 Audit Vision
audit = METADATA, TRACKER, CREATE, UPDATE, DELETE

# Allow remote server for webhook integration
route.remote_servers_allowed = http://api:8000

# Allow event webhook integration
event_hooks.enabled = on
