from typing import TypeVar, Generic, List, Optional, Any
from core.db.base import BoundBaseClass
from pydantic import BaseModel, ConfigDict
from sqlalchemy.orm import Session
from sqlalchemy import select, update, delete, func
from fastapi import HTTPException
from sqlalchemy.exc import IntegrityError


# Define generic type variables

T = TypeVar("T", bound=BoundBaseClass)  # SQLAlchemy model type
CreateSchema = TypeVar("CreateSchema", bound=BaseModel)
ReadSchema = TypeVar("ReadSchema", bound=BaseModel)


class PaginatedResponse(BaseModel, Generic[ReadSchema]):
    total: int
    page: int
    per_page: int
    data: List[ReadSchema]

    model_config = ConfigDict(
        from_attributes = True
    )

# Generic CRUD Class


class CRUDBase(Generic[T, CreateSchema, ReadSchema]):

    def __init__(self, model: type[T]):
        self.model = model

    def get_total(self, db: Session):
        query = select(func.count()).select_from(self.model)
        return db.execute(query).scalar()

    def get(self, db: Session, id: str) -> ReadSchema:

        if id is None:
            raise HTTPException(status_code=404, detail=f"{self.model.__name__} id needed")

        query = select(self.model).where(self.model.id == id)

        result = db.execute(query)
        obj = result.scalar_one_or_none()

        if obj is None:
            raise HTTPException(status_code=404, detail=f"{self.model.__name__} not found")

        return obj

    def get_all(self, db: Session, *, page: int = 1, pageSize: int = 100) -> PaginatedResponse[ReadSchema]:

        skip = (page - 1) * pageSize
        total = self.get_total(db)

        query = select(self.model).offset(skip).limit(pageSize)
        result = db.execute(query)
        data = result.scalars().all()

        # paginated_response = PaginatedResponse[ReadSchema](
        #     data=data,
        #     total=total,
        #     page=page,
        #     per_page=pageSize
        # )
        # return paginated_response
        return data

    def create(self, db: Session, *, payload_in: CreateSchema) -> ReadSchema:
        
        payload = payload_in.model_dump(exclude_unset=True)  # Exclude unset fields (e.g., id=None)
        provided_id = payload.get("id")

        try:
            if provided_id:
                # Check if a record with the provided ID exists
                query = select(self.model).where(self.model.id == provided_id)
                result = db.execute(query)
                existing_obj = result.scalar_one_or_none()

                if existing_obj:
                    # Update existing record, excluding the id field
                    update_data = {k: v for k, v in payload.items() if k != "id"}
                    query = (
                        update(self.model)
                        .where(self.model.id == provided_id)
                        .values(**update_data)
                        .returning(self.model)
                    )
                    result = db.execute(query)
                    db.commit()
                    updated_obj = result.scalar_one()
                    db.refresh(updated_obj)
                    return updated_obj

            # Create a new record (with provided id or generated by generate_custom_id)
            db_obj = self.model(**payload)
            db.add(db_obj)
            db.commit()
            db.refresh(db_obj)
            return db_obj
        except IntegrityError as e:
            raise HTTPException(status_code=400, detail=str(e))

    def delete(self, db: Session, *, id: str) -> None:

        query = delete(self.model).where(self.model.id == id)
        result = db.execute(query)

        if result.rowcount == 0:
            raise HTTPException(status_code=404, detail=f"{self.model.__name__} not found")
        db.commit()
